/*
 * Copyright 2019 Orient Securities Co., Ltd.
 * Copyright 2019 BoCloud Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.orientsec.grpc.service.routeguide;

public final class RouteGuideProto {
  private RouteGuideProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_routeguide_Point_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_routeguide_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_routeguide_Rectangle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_routeguide_Rectangle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_routeguide_Feature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_routeguide_Feature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_routeguide_FeatureDatabase_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_routeguide_FeatureDatabase_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_routeguide_RouteNote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_routeguide_RouteNote_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_routeguide_RouteSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_routeguide_RouteSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021route_guide.proto\022%com.orientsec.grpc." +
      "service.routeguide\",\n\005Point\022\020\n\010latitude\030" +
      "\001 \001(\005\022\021\n\tlongitude\030\002 \001(\005\"\177\n\tRectangle\0228\n" +
      "\002lo\030\001 \001(\0132,.com.orientsec.grpc.service.r" +
      "outeguide.Point\0228\n\002hi\030\002 \001(\0132,.com.orient" +
      "sec.grpc.service.routeguide.Point\"W\n\007Fea" +
      "ture\022\014\n\004name\030\001 \001(\t\022>\n\010location\030\002 \001(\0132,.c" +
      "om.orientsec.grpc.service.routeguide.Poi" +
      "nt\"R\n\017FeatureDatabase\022?\n\007feature\030\001 \003(\0132." +
      ".com.orientsec.grpc.service.routeguide.F",
      "eature\"\\\n\tRouteNote\022>\n\010location\030\001 \001(\0132,." +
      "com.orientsec.grpc.service.routeguide.Po" +
      "int\022\017\n\007message\030\002 \001(\t\"b\n\014RouteSummary\022\023\n\013" +
      "point_count\030\001 \001(\005\022\025\n\rfeature_count\030\002 \001(\005" +
      "\022\020\n\010distance\030\003 \001(\005\022\024\n\014elapsed_time\030\004 \001(\005" +
      "2\335\003\n\nRouteGuide\022l\n\nGetFeature\022,.com.orie" +
      "ntsec.grpc.service.routeguide.Point\032..co" +
      "m.orientsec.grpc.service.routeguide.Feat" +
      "ure\"\000\022t\n\014ListFeatures\0220.com.orientsec.gr" +
      "pc.service.routeguide.Rectangle\032..com.or",
      "ientsec.grpc.service.routeguide.Feature\"" +
      "\0000\001\022t\n\013RecordRoute\022,.com.orientsec.grpc." +
      "service.routeguide.Point\0323.com.orientsec" +
      ".grpc.service.routeguide.RouteSummary\"\000(" +
      "\001\022u\n\tRouteChat\0220.com.orientsec.grpc.serv" +
      "ice.routeguide.RouteNote\0320.com.orientsec" +
      ".grpc.service.routeguide.RouteNote\"\000(\0010\001" +
      "B@\n%com.orientsec.grpc.service.routeguid" +
      "eB\017RouteGuideProtoP\001\242\002\003RTGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_orientsec_grpc_service_routeguide_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_orientsec_grpc_service_routeguide_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_routeguide_Point_descriptor,
        new String[] { "Latitude", "Longitude", });
    internal_static_com_orientsec_grpc_service_routeguide_Rectangle_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_orientsec_grpc_service_routeguide_Rectangle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_routeguide_Rectangle_descriptor,
        new String[] { "Lo", "Hi", });
    internal_static_com_orientsec_grpc_service_routeguide_Feature_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_orientsec_grpc_service_routeguide_Feature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_routeguide_Feature_descriptor,
        new String[] { "Name", "Location", });
    internal_static_com_orientsec_grpc_service_routeguide_FeatureDatabase_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_orientsec_grpc_service_routeguide_FeatureDatabase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_routeguide_FeatureDatabase_descriptor,
        new String[] { "Feature", });
    internal_static_com_orientsec_grpc_service_routeguide_RouteNote_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_orientsec_grpc_service_routeguide_RouteNote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_routeguide_RouteNote_descriptor,
        new String[] { "Location", "Message", });
    internal_static_com_orientsec_grpc_service_routeguide_RouteSummary_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_orientsec_grpc_service_routeguide_RouteSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_routeguide_RouteSummary_descriptor,
        new String[] { "PointCount", "FeatureCount", "Distance", "ElapsedTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
