/*
 * Copyright 2019 Orient Securities Co., Ltd.
 * Copyright 2019 BoCloud Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.orientsec.grpc.service;

public interface CommonReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.orientsec.grpc.service.CommonReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>optional string message = 2;</code>
   */
  String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional int32 no = 3;</code>
   */
  int getNo();

  /**
   * <code>optional double salary = 4;</code>
   */
  double getSalary();

  /**
   * <code>optional int64 total = 5;</code>
   */
  long getTotal();
}
