// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.orientsec.grpc.service;

public interface CommonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.orientsec.grpc.service.CommonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 no = 1;</code>
   */
  int getNo();

  /**
   * <code>optional string name = 2;</code>
   */
  String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional bool sex = 3;</code>
   */
  boolean getSex();

  /**
   * <code>optional double salary = 4;</code>
   */
  double getSalary();

  /**
   * <code>optional string desc = 5;</code>
   */
  String getDesc();
  /**
   * <code>optional string desc = 5;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
