// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.orientsec.grpc.service;

public final class GreeterProto {
  private GreeterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_GreeterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_GreeterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_GreeterReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_GreeterReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_CommonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_CommonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_CommonReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_CommonReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rgreeter.proto\022\032com.orientsec.grpc.serv" +
      "ice\"\036\n\016GreeterRequest\022\014\n\004name\030\001 \001(\t\"\037\n\014G" +
      "reeterReply\022\017\n\007message\030\001 \001(\t\"T\n\rCommonRe" +
      "quest\022\n\n\002no\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\013\n\003sex\030\003" +
      " \001(\010\022\016\n\006salary\030\004 \001(\001\022\014\n\004desc\030\005 \001(\t\"Z\n\013Co" +
      "mmonReply\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 " +
      "\001(\t\022\n\n\002no\030\003 \001(\005\022\016\n\006salary\030\004 \001(\001\022\r\n\005total" +
      "\030\005 \001(\0032\311\002\n\007Greeter\022b\n\010sayHello\022*.com.ori" +
      "entsec.grpc.service.GreeterRequest\032(.com" +
      ".orientsec.grpc.service.GreeterReply\"\000\022n",
      "\n\026doSomethingForLongTime\022).com.orientsec" +
      ".grpc.service.CommonRequest\032\'.com.orient" +
      "sec.grpc.service.CommonReply\"\000\022j\n\022checkM" +
      "ethodInvoked\022).com.orientsec.grpc.servic" +
      "e.CommonRequest\032\'.com.orientsec.grpc.ser" +
      "vice.CommonReply\"\000B,\n\032com.orientsec.grpc" +
      ".serviceB\014GreeterProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_orientsec_grpc_service_GreeterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_orientsec_grpc_service_GreeterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_GreeterRequest_descriptor,
        new String[] { "Name", });
    internal_static_com_orientsec_grpc_service_GreeterReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_orientsec_grpc_service_GreeterReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_GreeterReply_descriptor,
        new String[] { "Message", });
    internal_static_com_orientsec_grpc_service_CommonRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_orientsec_grpc_service_CommonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_CommonRequest_descriptor,
        new String[] { "No", "Name", "Sex", "Salary", "Desc", });
    internal_static_com_orientsec_grpc_service_CommonReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_orientsec_grpc_service_CommonReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_CommonReply_descriptor,
        new String[] { "Success", "Message", "No", "Salary", "Total", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
