// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.orientsec.grpc.service;

public interface GreeterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.orientsec.grpc.service.GreeterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
