// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.orientsec.grpc.service;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_PersonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_PersonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_PersonReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_PersonReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014person.proto\022\025com.dfzq.grpc.service\"\033\n" +
      "\rPersonRequest\022\n\n\002no\030\001 \001(\005\"f\n\013PersonRepl" +
      "y\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\022\n\n\002n" +
      "o\030\003 \001(\005\022\014\n\004name\030\004 \001(\t\022\013\n\003age\030\005 \001(\005\022\016\n\006sa" +
      "lary\030\006 \001(\0012a\n\nPersonInfo\022S\n\005query\022$.com." +
      "dfzq.grpc.service.PersonRequest\032\".com.ht" +
      "sc.grpc.service.PersonReply\"\0002e\n\nPersonN" +
      "ame\022W\n\tqueryName\022$.com.orientsec.grpc.service" +
      ".PersonRequest\032\".com.orientsec.grpc.service.P" +
      "ersonReply\"\0002c\n\tPersonAge\022V\n\010queryAge\022$.",
      "com.orientsec.grpc.service.PersonRequest\032\".co" +
      "m.dfzq.grpc.service.PersonReply\"\0002i\n\014Per" +
      "sonSalary\022Y\n\013querySalary\022$.com.orientsec.grpc" +
      ".service.PersonRequest\032\".com.orientsec.grpc.s" +
      "ervice.PersonReply\"\000B&\n\025com.dfzq.grpc.se" +
      "rviceB\013PersonProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_orientsec_grpc_service_PersonRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_orientsec_grpc_service_PersonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_PersonRequest_descriptor,
        new String[] { "No", });
    internal_static_com_orientsec_grpc_service_PersonReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_orientsec_grpc_service_PersonReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_PersonReply_descriptor,
        new String[] { "Success", "Message", "No", "Name", "Age", "Salary", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
