// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.orientsec.grpc.service;

public interface PersonReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.orientsec.grpc.service.PersonReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>optional string message = 2;</code>
   */
  String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional int32 no = 3;</code>
   */
  int getNo();

  /**
   * <code>optional string name = 4;</code>
   */
  String getName();
  /**
   * <code>optional string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 age = 5;</code>
   */
  int getAge();

  /**
   * <code>optional double salary = 6;</code>
   */
  double getSalary();
}
