// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.orientsec.grpc.service;

public interface PersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.orientsec.grpc.service.PersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 no = 1;</code>
   */
  int getNo();
}
