// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query.proto

package com.orientsec.grpc.service;

public interface QueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.orientsec.grpc.service.QueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 no = 1;</code>
   */
  int getNo();

  /**
   * <code>optional string name = 2;</code>
   */
  String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string alias = 3;</code>
   */
  String getAlias();
  /**
   * <code>optional string alias = 3;</code>
   */
  com.google.protobuf.ByteString
      getAliasBytes();

  /**
   * <code>optional bool sex = 4;</code>
   */
  boolean getSex();

  /**
   * <code>optional double salary = 5;</code>
   */
  double getSalary();

  /**
   * <code>optional uint64 total = 6;</code>
   */
  long getTotal();

  /**
   * <code>optional string desc = 7;</code>
   */
  String getDesc();
  /**
   * <code>optional string desc = 7;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>optional string misc = 8;</code>
   */
  String getMisc();
  /**
   * <code>optional string misc = 8;</code>
   */
  com.google.protobuf.ByteString
      getMiscBytes();
}
