// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query.proto

package com.orientsec.grpc.service;

public final class QueryProto {
  private QueryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_QueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orientsec_grpc_service_QueryReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orientsec_grpc_service_QueryReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013query.proto\022\025com.dfzq.grpc.service\"\177\n\014" +
      "QueryRequest\022\n\n\002no\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r" +
      "\n\005alias\030\003 \001(\t\022\013\n\003sex\030\004 \001(\010\022\016\n\006salary\030\005 \001" +
      "(\001\022\r\n\005total\030\006 \001(\004\022\014\n\004desc\030\007 \001(\t\022\014\n\004misc\030" +
      "\010 \001(\t\"\216\001\n\nQueryReply\022\n\n\002no\030\001 \001(\005\022\014\n\004name" +
      "\030\002 \001(\t\022\r\n\005alias\030\003 \001(\t\022\013\n\003sex\030\004 \001(\010\022\016\n\006sa" +
      "lary\030\005 \001(\001\022\r\n\005total\030\006 \001(\004\022\014\n\004desc\030\007 \001(\t\022" +
      "\014\n\004misc\030\010 \001(\t\022\017\n\007message\030\t \001(\t2Z\n\005Query\022" +
      "Q\n\005query\022#.com.orientsec.grpc.service.QueryRe" +
      "quest\032!.com.orientsec.grpc.service.QueryReply",
      "\"\000B%\n\025com.dfzq.grpc.serviceB\nQueryProtoP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_orientsec_grpc_service_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_orientsec_grpc_service_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_QueryRequest_descriptor,
        new String[] { "No", "Name", "Alias", "Sex", "Salary", "Total", "Desc", "Misc", });
    internal_static_com_orientsec_grpc_service_QueryReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_orientsec_grpc_service_QueryReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orientsec_grpc_service_QueryReply_descriptor,
        new String[] { "No", "Name", "Alias", "Sex", "Salary", "Total", "Desc", "Misc", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
